SELECT INI
	,ITEM
	,VALUE_C
	,NAME
	,TITLE
	,ABBR
	,INTERNAL_ID
	,IS_ACTIVE_YN
FROM ALL_CATEGORIES
WHERE INI = 'EPT'
	AND ITEM = 30

SELECT DISP_ENC_TYPE_C
	,NAME
	,TITLE
	,ABBR
	,INTERNAL_ID
FROM ZC_DISP_ENC_TYPE

SELECT 
	TABLE_NAME
	,EXTRACT_FILENAME
	,RELEASED_VERSION_C
	,LAST_MOD_VERSION_C
	,BS_TEMPLATE_ID
	,DEPENDENT_INI
	,IS_JOB_DIVIDED_YN
	,IS_EXTRACTED_YN
	,LOAD_FREQUENCY
	,LOAD_TYPE
	,ROUTINE_NAME
	,ORA_DATA_TBLSPACE
	,ORA_INDEX_TBLSPACE
	,ORA_OVRFL_TBLSPACE
	,IS_PARTITIONED_YN
	,PARTITION_TYPE
	,PARTITION_RANGE
	,PARTITION_KEY
	,IS_IX_ORGANIZED_YN
	,SUB_PARTITION_KEY
	,SUB_PARTITION_VAL
	,TBL_DESCRIPTOR
	,TBL_DESCRIPTOR_OVR
	,TABLE_INTRODUCTION
	,CHRONICLES_MF
	,CM_PHY_OWNER_ID
	,CM_LOG_OWNER_ID
	,IS_PRESERVED_YN
	,ORA_STG_TBLSPACE
	,ORA_STG_OVRFLTBLSP
	,TABLE_NOTES
	,DATA_RETAINED_YN
	,DEPRECATED_YN
	,EXTRACT_TEMPLATE_C
FROM CLARITY_TBL
WHERE (
		TABLE_NAME IN (
			'ZC_DISP_ENC_TYPE'
			,'ALL_CATEGORIES'
			)
		)
	AND (TABLE_ID LIKE 'C%')
ORDER BY TABLE_NAME
